apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-memory
  namespace: ngsa
  labels:
    app.kubernetes.io/name: ngsa-memory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa-memory
  template:
    metadata:
      labels:
        app: ngsa-memory
        version: beta-2208-24-15
        deploy: 22-08-24-15-48-33
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-app:beta
          imagePullPolicy: Always
          args: 
          - --in-memory
          - --prometheus
          - --zone
          - az-westus2-pre
          - --region
          - westus2
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /version
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /healthz
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - emptyDir: {}
          name: tmp
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        agentpool: npuser01

---
apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ngsa-memory

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ngsa-memory-vs
  namespace: ngsa
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - ngsa-memory-westus2-pre.cse.ms
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: ngsa-memory
