apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: burst-wasm-remote
  namespace: ngsa
spec:
  workloadSelector:
    labels:
      app: ngsa-cosmos
  configPatches:
  # The patch adds the WebAssembly to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      # the patch adds the WebAssembly to the pipeline
      operation: INSERT_BEFORE 
      value:
        name: burst-wasm-extension
        config_discovery:
          config_source:
            ads: {}
            initial_fetch_timeout: 0s # wait indefinitely to prevent bad Wasm fetch
          type_urls: [ "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm" ]

  # The second patch provides config for filter, wasm http location
  - applyTo: EXTENSION_CONFIG
    match:
      context: SIDECAR_INBOUND
    patch:
      operation: INSERT_BEFORE
      value:
        name: burst-wasm-extension
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              # The configuration for the Wasm extension itself
              configuration:
                "@type": "type.googleapis.com/google.protobuf.StringValue"
                value: |
                  { 
                    "service_cluster": "burstcluster",
                    "service_authority": "burst.burstservice",
                    "service_path": "/burstmetrics/deployments",
                    "cache_seconds": 5
                  }    
              root_id: burst-wasm-root-id
              vm_config:
                vm_id: burst-wasm-vm-id
                runtime: envoy.wasm.runtime.v8
                allow_precompiled: true
                code:
                  remote:
                    http_uri:
                      uri: https://raw.githubusercontent.com/retaildevcrews/ngsa-asb/main/wasm/burst_header.wasm
                      cluster: burstcluster
                      timeout: 10s
                    sha256: 0f54aa9a06f06dc0adb8b155c69b0883dd009c96b87f9f985fb2bee197c46c6d       

  # The  patch adds the cluster that is referenced by the WebAssembly
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        name: "burstcluster"
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        connect_timeout: 0.5s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: burstcluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: TCP
                    address: burst.burstservice
                    port_value: 8080
