apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-default
spec:
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: "/dev/stdout"
    accessLogFormat: |
      {
        "start_time": "%START_TIME%",
        "request_method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "protocol": "%PROTOCOL%",
        "response_code": "%RESPONSE_CODE%",
        "response_code_details": "%RESPONSE_CODE_DETAILS%",
        "response_flags": "%RESPONSE_FLAGS%",
        "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
        "bytes_received": "%BYTES_RECEIVED%",
        "bytes_sent": "%BYTES_SENT%",
        "duration": "%DURATION%",
        "x_envoy_upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "user_agent": "%REQ(USER-AGENT)%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "x_b3_traceid": "%REQ(X-B3-TRACEID)%",
        "x_b3_spanid": "%REQ(X-B3-SPANID)%",
        "request_authority": "%REQ(:AUTHORITY)%",
        "host": "%UPSTREAM_HOST%",
        "upstream_cluster": "%UPSTREAM_CLUSTER%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "route_name": "%ROUTE_NAME%"
      }
  profile: default
  hub: ghcr.io/retaildevcrews/istio
  components:
    pilot:
      k8s:
        resources:
          limits:
            cpu: 1000m
            memory: 512M
          requests:
            cpu: 500m
            memory: 256M
    ingressGateways:
    - name: istio-ingressgateway
      label:
        aadpodidbinding: podmi-ingress-controller
      k8s:
        resources:
          limits:
            cpu: 1000m
            memory: 512M
          requests:
            cpu: 500m
            memory: 256M
        nodeSelector:
          agentpool: npuser01
        service:
          type: LoadBalancer
          loadBalancerIP: 10.240.4.4
          externalTrafficPolicy: Local
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-clusteringressservices"
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.volumes[name:ingressgateway-certs]
            value:
              name: ingressgateway-certs
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: istio-ingress-tls-secret-csi-akv
