apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-java
  namespace: ngsa
  labels:
    app.kubernetes.io/name: ngsa-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa-java
  template:
    metadata:
      labels:
        aadpodidbinding: ngsa-asb-ngsa-id
        app: ngsa-java
        deploy: 22-02-23-21-05-57
        version: beta-2202-23-21
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-java:beta
          imagePullPolicy: Always
          env:
          - name: PROMETHEUS
            value: "true"
          - name: ZONE
            value: "az-centralus-pre"
          - name: REGION
            value: "centralus"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /version
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /healthz
              port: 8080              
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ngsa-secrets
      nodeSelector:
        agentpool: npuser01

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-java
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ngsa-java

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ngsa-java-vs
  namespace: ngsa
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - ngsa-java-centralus-pre.cse.ms
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: ngsa-java
