apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner-ui
  namespace: loderunner
  labels:
    app.kubernetes.io/name: loderunner-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner-ui
  template:
    metadata:
      labels:
        app: loderunner-ui
        deploy: 22-05-17-06-03-45
        version: beta-2205-17-06
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/lr-ui:beta
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          env:
          - name: "LRAPI_DNS"
            value: "https://loderunner-westus2-dev.cse.ms/api"
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 80
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /
              port: 80
      nodeSelector:
        agentpool: npuser01
        
---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-ui
  namespace: loderunner
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http 
    protocol: TCP
    name: http
  selector:
    app: loderunner-ui
    
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: loderunner-vs
  namespace: loderunner
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - loderunner-westus2-dev.cse.ms
  http:
  - match:
    - uri:
        prefix: /api/
    - uri:
        exact: /api
    rewrite:
      uri: /
    route:
    - destination:
        host: loderunner-api
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: loderunner-ui
        port:
          number: 80
