apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner-clientmode
  namespace: loderunner
  labels:
    app.kubernetes.io/name: loderunner-clientmode
  annotations:
    checkov.io/skip1: CKV_K8S_8=LR Client does not have liveness endpoint
    checkov.io/skip2: CKV_K8S_9=LR Client does not have readiness endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner-clientmode
  template:
    metadata:
      labels:
        app: loderunner-clientmode
        aadpodidbinding: ngsa-asb-loderunner-id
        deploy: 22-08-25-13-35-12
        version: beta-2208-25-13
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-lr:beta
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          args: 
          - --mode 
          - Client
          - --secrets-volume
          - /app/secrets
          - --prometheus
          - --zone
          - az-westus2-dev
          - --region
          - westus2
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
            - mountPath: /tmp
              name: tmp
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: lr-secrets
        - name: tmp
          emptyDir: {}
      nodeSelector:
        agentpool: npuser01

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-clientmode
  namespace: loderunner
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http 
      protocol: TCP
      name: http
  selector:
    app: loderunner-clientmode
